# Generated by Django 2.1.7 on 2019-02-19 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100, verbose_name='章节名称')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='章节添加时间')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('description', models.TextField(max_length=500, verbose_name='课程描述')),
                ('detail', models.TextField(verbose_name='课程详情')),
                ('degree', models.CharField(choices=[('easy', '初级'), ('normal', '中级'), ('hard', '高级')], max_length=10, verbose_name='课程难度')),
                ('learn_times', models.IntegerField(default=0, verbose_name='学习时长（分钟数）')),
                ('student_number', models.IntegerField(default=0, verbose_name='学习人数')),
                ('collect_number', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('course_mark', models.FloatField(default=10.0, verbose_name='课程总评分')),
                ('course_image', models.ImageField(max_length=500, upload_to='courses/static/courses/image/%Y/%m', verbose_name='课程图片')),
                ('click_number', models.IntegerField(default=0, verbose_name='点击量')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='课程添加时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=50, verbose_name='资源名称')),
                ('download', models.FileField(max_length=200, upload_to='courses/static/courses/resource/%Y/%m', verbose_name='资源文件')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='资源添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程相关资源')),
            ],
            options={
                'verbose_name': '课程相关资源',
                'verbose_name_plural': '课程相关资源',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100, verbose_name='章节名称')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='小节添加时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter', verbose_name='小节名称')),
            ],
            options={
                'verbose_name': '小节',
                'verbose_name_plural': '小节',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='章节名称'),
        ),
    ]
