# Generated by Django 2.1.7 on 2019-02-20 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='lesson_name',
            new_name='chapter_name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='lesson_name',
        ),
        migrations.AddField(
            model_name='section',
            name='section_name',
            field=models.CharField(default='a', max_length=100, verbose_name='小节名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='section',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter', verbose_name='章节名'),
        ),
    ]
