# Generated by Django 2.1.7 on 2019-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190220_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(max_length=500, upload_to='apps/courses/static/courses/image/%Y/%m', verbose_name='课程图片'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(max_length=200, upload_to='apps/courses/static/courses/resource/%Y/%m', verbose_name='资源文件'),
        ),
    ]
