# Generated by Django 2.1.7 on 2019-02-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190220_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(max_length=500, upload_to='apps/courses/static/courses/images/%Y/%m', verbose_name='课程图片'),
        ),
    ]
