# Generated by Django 2.1.7 on 2019-02-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20190227_0018'),
        ('courses', '0006_auto_20190221_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrganization', to_field='organization_name', verbose_name='课程提供方'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('open', '公开课'), ('specialized', '专业课')], default='open', max_length=20, verbose_name='课程类型'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(max_length=500, upload_to='courses/images/%Y/%m', verbose_name='课程图片'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(max_length=200, upload_to='courses/resources/%Y/%m', verbose_name='资源文件'),
        ),
    ]
