# Generated by Django 2.1.7 on 2019-02-27 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190227_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrganization', verbose_name='课程提供方'),
        ),
    ]
