# Generated by Django 2.1.7 on 2019-02-28 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190227_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_courseorganization', to='organizations.CourseOrganization', verbose_name='课程提供方'),
        ),
    ]
