# Generated by Django 2.1.7 on 2019-02-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190228_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_attr',
            field=models.CharField(choices=[('Web_front', 'Web前端'), ('Web_after', 'Web后端')], default='Web_after', max_length=20, verbose_name='课程属性'),
        ),
    ]
