# Generated by Django 2.1.7 on 2019-02-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_course_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.CharField(choices=[('Web_develop', 'Web开发'), ('HTML5_develop', 'HTML5开发')], default='Web_develop', max_length=20, verbose_name='课程类别'),
        ),
    ]
