# Generated by Django 2.1.7 on 2019-03-03 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_teacher_course_number'),
        ('courses', '0012_course_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='organizations.Teacher', verbose_name='课程教师'),
            preserve_default=False,
        ),
    ]
