# Generated by Django 2.1.7 on 2019-03-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_attr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_provider',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_mark',
            field=models.FloatField(default=10.0, verbose_name='课程评分'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=30, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=50, verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='学习时长'),
        ),
    ]
