# Generated by Django 2.1.7 on 2019-03-03 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190303_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_category', models.CharField(max_length=20, verbose_name='课程大类')),
            ],
            options={
                'verbose_name': '课程大类',
                'verbose_name_plural': '课程大类',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(max_length=20, verbose_name='课程小类')),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseCategory', verbose_name='课程小类所属的大类')),
            ],
            options={
                'verbose_name': '课程小类',
                'verbose_name_plural': '课程小类',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='open_type',
            field=models.CharField(choices=[('open', '公开课'), ('specialized', '专业课')], default='open', max_length=20, verbose_name='课程类型'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseType', verbose_name='课程小类'),
        ),
    ]
