# Generated by Django 2.1.7 on 2019-03-03 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20190303_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
