# Generated by Django 2.1.7 on 2019-03-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20190303_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_announcement',
            field=models.CharField(default='', max_length=200, verbose_name='课程公告'),
        ),
    ]
