# Generated by Django 2.1.7 on 2019-03-04 03:59

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_course_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_content',
            field=models.FileField(default='', upload_to=courses.models.get_upload_section_path, verbose_name='课程小结内容文件'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(max_length=500, upload_to=courses.models.get_upload_course_image_path, verbose_name='课程图片'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(max_length=200, upload_to=courses.models.get_upload_course_resource_path, verbose_name='资源文件'),
        ),
    ]
