# Generated by Django 2.1.7 on 2019-03-04 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20190304_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_announcement', models.CharField(default='', max_length=200, verbose_name='课程公告')),
            ],
            options={
                'verbose_name': '课程公告',
                'verbose_name_plural': '课程公告',
            },
        ),
        migrations.CreateModel(
            name='CourseNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_notice', models.CharField(default='', max_length=200, verbose_name='课程须知')),
            ],
            options={
                'verbose_name': '课程须知',
                'verbose_name_plural': '课程须知',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_announcement',
        ),
        migrations.AddField(
            model_name='coursenotice',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='关联课程'),
        ),
        migrations.AddField(
            model_name='courseinformation',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='关联课程'),
        ),
    ]
