# Generated by Django 2.1.7 on 2019-03-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20190304_0554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseInformation',
            new_name='CourseAnnouncement',
        ),
    ]
