# Generated by Django 2.1.7 on 2019-03-04 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20190304_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseannouncement',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='coursenotice',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
