# Generated by Django 2.1.7 on 2019-03-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20190304_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursenotice',
            name='course_goal',
            field=models.CharField(default='', max_length=200, verbose_name='课程目标'),
        ),
        migrations.AlterField(
            model_name='coursenotice',
            name='course_notice',
            field=models.CharField(default='', max_length=200, verbose_name='课程基础'),
        ),
    ]
