# Generated by Django 2.1.7 on 2019-03-05 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20190304_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10, verbose_name='标签')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程标签',
                'verbose_name_plural': '课程标签',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_tag',
            field=models.ManyToManyField(blank=True, to='courses.Tags', verbose_name='标签'),
        ),
    ]
