# Generated by Django 2.1.7 on 2019-03-05 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20190305_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to='organizations.Teacher', verbose_name='课程教师'),
        ),
    ]
