# Generated by Django 2.1.7 on 2019-03-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_course_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_banner',
            field=models.CharField(choices=[(False, '否'), (True, '是')], default=False, max_length=10, verbose_name='是否处于轮播位'),
        ),
    ]
