# Generated by Django 2.1.7 on 2019-03-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20190308_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
                'proxy': True,
                'indexes': [],
            },
            bases=('courses.course',),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_banner',
            field=models.CharField(choices=[('False', '否'), ('True', '是')], default='False', max_length=10, verbose_name='是否处于轮播位'),
        ),
    ]
