# Generated by Django 2.1.7 on 2019-03-08 20:16

import DUEditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20190308_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DUEditor.models.UEditorField(blank=True, default='', verbose_name='课程详情'),
        ),
    ]
