# Generated by Django 2.1.7 on 2019-02-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='address',
            field=models.CharField(default='', max_length=150, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=5, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='head_portrait',
            field=models.ImageField(default='image/default.png', max_length=200, upload_to='image/%Y%D', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='nick_name',
            field=models.CharField(default='', max_length=50, verbose_name='昵称'),
        ),
    ]
