# Generated by Django 2.1.7 on 2019-02-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190218_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='head_portrait',
            field=models.ImageField(default='static/users/image/head_portrait/default.png', max_length=200, upload_to='static/users/image/head_portrait/%Y%D', verbose_name='头像'),
        ),
    ]
