# Generated by Django 2.1.7 on 2019-02-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190218_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='head_portrait',
            field=models.ImageField(default='users/static/users/image/head_portrait/default.png', max_length=200, upload_to='users/static/users/image/head_portrait/%Y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='viewpage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='users/static/users/image/view_page/%Y/%m', verbose_name='轮播图'),
        ),
    ]
