# Generated by Django 2.1.7 on 2019-02-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190219_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别'),
        ),
    ]
