# Generated by Django 2.1.7 on 2019-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190220_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=20, verbose_name='验证码类型'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='head_portrait',
            field=models.ImageField(default='apps/users/static/users/image/head_portrait/default.png', max_length=200, upload_to='apps/users/static/users/image/head_portrait/%Y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='viewpage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='apps/users/static/users/image/view_page/%Y/%m', verbose_name='轮播图'),
        ),
    ]
