# Generated by Django 2.1.7 on 2019-02-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190221_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='user_name',
            field=models.CharField(default=1, max_length=20, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
