# Generated by Django 2.1.7 on 2019-02-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_emailverifyrecord_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='user_name',
        ),
    ]
