# Generated by Django 2.1.7 on 2019-02-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_emailverifyrecord_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='verified_times',
            field=models.IntegerField(default=3),
        ),
    ]
