# Generated by Django 2.1.7 on 2019-02-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_emailverifyrecord_verified_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='head_portrait',
            field=models.ImageField(default='users/images/head_portrait/default.png', max_length=200, upload_to='users/images/head_portrait/%Y/%m', verbose_name='头像'),
        ),
    ]
