# Generated by Django 2.1.7 on 2019-02-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190227_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewpage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='users/images/view_page/%Y/%m', verbose_name='轮播图'),
        ),
    ]
