# Generated by Django 2.1.7 on 2019-03-04 03:59

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190227_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='head_portrait',
            field=models.ImageField(default='', max_length=200, upload_to=users.models.get_upload_user_image_path, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='viewpage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=users.models.get_upload_view_page_path, verbose_name='轮播图'),
        ),
    ]
