# Generated by Django 2.1.7 on 2019-03-06 22:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190306_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='head_portrait',
            field=models.ImageField(default='user/default_head_portrait/default.png', max_length=200, upload_to=users.models.get_upload_user_image_path, verbose_name='头像'),
        ),
    ]
