# Generated by Django 2.1.7 on 2019-03-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190306_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('reset_email', '重置邮箱')], max_length=20, verbose_name='验证码类型'),
        ),
    ]
