# Generated by Django 2.1.7 on 2019-03-08 01:20

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190307_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='head_portrait',
            field=models.ImageField(blank=True, default='user/default_head_portrait/default.png', max_length=200, upload_to=users.models.get_upload_user_image_path, verbose_name='头像'),
        ),
    ]
