# Generated by Django 2.1.7 on 2019-02-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercollection',
            options={'verbose_name': '用户收藏', 'verbose_name_plural': '用户收藏'},
        ),
    ]
