# Generated by Django 2.1.7 on 2019-02-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20190226_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userask',
            name='question',
        ),
    ]
