# Generated by Django 2.1.7 on 2019-03-04 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20190303_0355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0003_remove_userask_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_mark', models.FloatField(default=10.0, verbose_name='机构评分')),
                ('comment', models.CharField(max_length=300, verbose_name='评论')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='问询添加时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrganization', verbose_name='机构')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '机构评论',
                'verbose_name_plural': '机构评论',
            },
        ),
        migrations.CreateModel(
            name='TeacherComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_mark', models.FloatField(default=10.0, verbose_name='教师评分')),
                ('comment', models.CharField(max_length=300, verbose_name='评论')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='教师')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '教师评论',
                'verbose_name_plural': '教师评论',
            },
        ),
        migrations.AlterModelOptions(
            name='coursecomment',
            options={'verbose_name': '课程评论', 'verbose_name_plural': '课程评论'},
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='teacher_mark',
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
