# Generated by Django 2.1.7 on 2019-03-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20190304_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationcomment',
            old_name='course_mark',
            new_name='organization_mark',
        ),
    ]
