# Generated by Django 2.1.7 on 2019-03-04 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20190304_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcomment',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
