# Generated by Django 2.1.7 on 2019-03-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20190305_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollection',
            name='collection_id',
            field=models.IntegerField(default=0, verbose_name='被收藏对象的id'),
        ),
    ]
