# Generated by Django 2.1.7 on 2019-02-19 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20, verbose_name='城市名称')),
                ('description', models.CharField(max_length=500, verbose_name='城市描述')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='城市添加时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='CourseOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=50, verbose_name='授课机构名称')),
                ('description', models.TextField(verbose_name='机构描述')),
                ('collect_number', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_number', models.IntegerField(default=0, verbose_name='点击量')),
                ('organization_image', models.ImageField(max_length=500, upload_to='organizations/static/organizations/image/organization/%Y/%m', verbose_name='机构图片')),
                ('address', models.CharField(default='', max_length=150, verbose_name='机构地址')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='机构添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CityDict', verbose_name='机构所在地')),
            ],
            options={
                'verbose_name': '授课机构',
                'verbose_name_plural': '授课机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='教师名称')),
                ('description', models.TextField(verbose_name='教师描述')),
                ('teacher_mark', models.FloatField(default=10.0, verbose_name='教师总评分')),
                ('inauguration_company', models.CharField(max_length=50, verbose_name='就职公司')),
                ('company_position', models.CharField(max_length=50, verbose_name='公司职位')),
                ('work_year', models.IntegerField(default=0, verbose_name='工作年限')),
                ('collect_number', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_number', models.IntegerField(default=0, verbose_name='点击量')),
                ('teacher_image', models.ImageField(max_length=500, upload_to='organizations/static/organizations/image/teacher/%Y/%m', verbose_name='教师图片')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='教师添加时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrganization', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '授课讲师',
                'verbose_name_plural': '授课讲师',
            },
        ),
    ]
