# Generated by Django 2.1.7 on 2019-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorganization',
            name='organization_image',
            field=models.ImageField(max_length=500, upload_to='apps/organizations/static/organizations/image/organization/%Y/%m', verbose_name='机构图片'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(max_length=500, upload_to='apps/organizations/static/organizations/image/teacher/%Y/%m', verbose_name='教师图片'),
        ),
    ]
