# Generated by Django 2.1.7 on 2019-02-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20190221_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorganization',
            name='organization_type',
            field=models.CharField(choices=[('collage', '高校'), ('training_institution', '培训机构'), ('personal', '个人')], default=None, max_length=20, verbose_name='机构类型'),
            preserve_default=False,
        ),
    ]
