# Generated by Django 2.1.7 on 2019-02-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_courseorganization_organization_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorganization',
            name='organization_image',
            field=models.ImageField(max_length=500, upload_to='organizations/images/organization/%Y/%m', verbose_name='机构图片'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(max_length=500, upload_to='organizations/images/teacher/%Y/%m', verbose_name='教师图片'),
        ),
    ]
