# Generated by Django 2.1.7 on 2019-02-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20190226_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorganization',
            name='organization_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='授课机构名称'),
        ),
    ]
