# Generated by Django 2.1.7 on 2019-03-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20190228_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorganization',
            name='organization_mark',
            field=models.FloatField(default=10.0, verbose_name='机构评价'),
        ),
    ]
