# Generated by Django 2.1.7 on 2019-03-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_teacher_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorganization',
            name='course_number',
            field=models.IntegerField(default=0, verbose_name='机构课程数量'),
        ),
        migrations.AlterField(
            model_name='courseorganization',
            name='organization_mark',
            field=models.FloatField(default=10.0, verbose_name='机构评分'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course_number',
            field=models.IntegerField(default=0, verbose_name='教师课程数量'),
        ),
    ]
