# Generated by Django 2.1.7 on 2019-03-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_auto_20190304_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorganization',
            name='course_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course_number',
        ),
    ]
