# Generated by Django 2.1.7 on 2019-03-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_auto_20190305_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorganization',
            name='course_number',
            field=models.IntegerField(default=0, verbose_name='结构课程数量'),
        ),
    ]
