# Generated by Django 2.1.7 on 2019-03-06 22:22

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_courseorganization_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorganization',
            name='organization_image',
            field=models.ImageField(default='organization/default_images/organization_image_default.png', max_length=500, upload_to=organizations.models.get_upload_org_image_path, verbose_name='机构图片'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(default='organization/default_images/teacher_image_default.png', max_length=500, upload_to=organizations.models.get_upload_teacher_image_path, verbose_name='教师图片'),
        ),
    ]
