# Generated by Django 2.1.7 on 2019-03-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_auto_20190306_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorganization',
            name='tag',
            field=models.CharField(default='全国知名', max_length=10, verbose_name='机构标签'),
        ),
    ]
