# Generated by Django 2.1.7 on 2019-03-08 20:16

import DUEditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_auto_20190308_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorganization',
            name='course_number',
            field=models.IntegerField(default=0, verbose_name='机构课程数量'),
        ),
        migrations.AlterField(
            model_name='courseorganization',
            name='description',
            field=DUEditor.models.UEditorField(blank=True, default='', verbose_name='机构描述'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=DUEditor.models.UEditorField(blank=True, default='', verbose_name='机构描述'),
        ),
    ]
